# Generated by Django 6.0.1 on 2026-02-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments_payment_url_payments_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
