# Generated by Django 6.0.1 on 2026-01-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на видео урока",
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
